### ISSUE TITLE
Alternate links for USB-C to GC cable

### ISSUE THREAD

**Issue by Soundtoxin** [GregTurbo/Open-Frame1#6]
I think we need an alternate source for the cables in the readme. I ordered one from the Frame1 site over a month ago, and have heard basically nothing. They show as in-stock, so I assumed they were already made and would just be shipped out. Not sure what the deal is. I managed to get a cable from the B0xx site in under a week (ordered fewer *and* they cost a little more, though), and they also have the USB-C to N64 cables, so they should be listed as a source instead or additionally. I also think a guide for making your own cables would be good to have linked in the readme to reduce these points of failure in sourcing such an important part. I don't know of a good guide, hopefully someone else does. Otherwise one may need to be written/recorded.

**Comment by GregTurbo** [comment]
Your order includes 2 things that are not currently shipping (brook installation kits that are only for the soon-to-be released Frame1 wave). Your order would have shipped weeks ago otherwise

**Comment by Soundtoxin** [comment]
Thank you for the additional info, Greg. I still really do think it may be worth listing multiple sources / DIY methods for the cables in the future (so not sure the issue should be closed), but I'm glad to have cleared up my particular case now.
