### ISSUE TITLE
Could I use a wire instead of a Schottky DIODE?

### ISSUE THREAD

**Issue by zerinsakech** [GregTurbo/Open-Frame1#7]
The instructions make it seem like a Diode is needed regardless whether you use the additional Connections (for direct GameCube controller port I assume?) Since most case designs for the Open1 don't seem to include this extra port, and it's cheaper/easier to make a USB C to GameCube cable instead of designing a case with the port, can we just wire up a solid wire (0 ohm) instead of a DIODE? I'm trying to save money and costs so wondering if this is a good alternate instruction to add to the Readme?

![Diode or wire](https://github.com/GregTurbo/Open-Frame1/assets/7526290/58d5c7e5-e81f-46f5-9a93-6b4aa228e44b)

**Comment by GregTurbo** [comment]
There is no second port, the usb-c connector handles USB or GCC connections with their respective cables. The unpopulated header on the right there is just for the sake of mods or troubleshooting.

If you're ONLY ever going to use USB, and don't plan on using a GameCube connection, DO NOT use a wire. Instead, just don't populate the diode at all. USB will work fine and you can always add the diode later anyway

**Comment by zerinsakech** [comment]
Thanks for the clarification!
